### ISSUE TITLE
When I run example_free_water.py, it reports a name error: name 'ct_att' undefined

### ISSUE THREAD

**Issue by 1413194910** [pty0220/FUS_acousitc_simulation#1]
Do I need to change this sentence? #ct_att = 0 + (20 - 0)*PI
lpha_coeff_np  = ct_att
![1716951674538](https://github.com/pty0220/FUS_acousitc_simulation/assets/60837815/83d6f6c0-a9bd-4de9-a763-373c949b2dc9)

**Comment by pty0220** [comment]
```
  ct_att          = a_bone_min + (a_bone_max-a_bone_min)*np.power(PI, 0.5)
  ct_att[PI==1]   = a_water
```

You need to add this codes

**Comment by 1413194910** [comment]
I have followed your advice and the problem has been successfully resolved. Thank you very much for your help!
